name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "CONFIG_PATH=prod.yaml" > .env
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> .env

      - name: Build Docker image
        run: |
          docker build -t oxeee/discount-code-bot:latest .

      - name: Stop and remove old container (if exists)
        run: |
          docker-compose down || true

      - name: Deploy new container via docker-compose
        run: |
          docker-compose up -d
